# Generated by Django 5.2.6 on 2025-09-12 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo da paciente", max_length=100
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "telefone",
                    models.CharField(help_text="(XX) XXXXX-XXXX", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "endereco",
                    models.TextField(blank=True, null=True, verbose_name="Endereço"),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Cadastro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Nome do procedimento", max_length=100),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço"
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento",
                "verbose_name_plural": "Procedimentos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(verbose_name="Data e Hora do Agendamento"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("realizado", "Realizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="agendado",
                        max_length=10,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "procedimento_realizado",
                    models.BooleanField(
                        default=False, verbose_name="Procedimento já foi realizado?"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="clinica.paciente",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agendamentos",
                        to="clinica.procedimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["-data_hora"],
            },
        ),
    ]
