# Generated by Django 5.2.6 on 2025-09-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="procedimento",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="procedimentos",
            field=models.ManyToManyField(
                related_name="agendamentos", to="clinica.procedimento"
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name="Valor Total"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
